// Adam Smith
// Projecteuler.net problem #2
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be :
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even - valued terms.
#include <iostream>
#include <vector>
using namespace std;

void fiber(int a, int b, vector<int>& evenFibs) {
	if ((a % 2) == 0)
		evenFibs.push_back(a);
	int c = (a + b);
	if (c > 8000000)
		return;
	fiber(b, c, evenFibs);
};

int main()
{
	int fibSum = 0;
	vector<int> evenFibs;
	fiber(1, 2, evenFibs);
	for (int i = 0; i < evenFibs.size(); ++i) {
		fibSum = fibSum + evenFibs[i];
	}
	cout << fibSum;

	cout << "\nPress Enter to Continue";
	getchar();
	return 0;
}